FROM debian:bullseye
RUN apt update -y
RUN apt upgrade -y
RUN apt-get install mariadb-server mariadb-client -y
RUN apt install vim -y && apt install curl -y
COPY conf/50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf
COPY tools/script.sh /etc/script.sh

RUN chmod +x /etc/script.sh

EXPOSE  3306

CMD ["./etc/script.sh"]

