FROM debian:bullseye
RUN apt-get update
run apt-get upgrade
RUN apt-get -y install wget
# RUN apt-get install -y php7.3\
# php-fpm\
# php-mysql\
# mariadb-client
RUN apt-get install -y php7.3 php-fpm php-mysql mariadb-client
RUN wget https://fr.wordpress.org/wordpress-6.0-fr_FR.tar.gz -P /var/www
RUN cd /var/www && tar -xzf wordpress-6.0-fr_FR.tar.gz && rm wordpress-6.0-fr_FR.tar.gz
RUN		chown -R root:root /var/www/wordpress
RUN apt install vim -y
# COPY tools/script.sh /var/www/wordpress/
----------------------------------------------------------
# (
#         J’ai ajouté une ligne  clear_env = no , je pense que cette ligne est assez claire pour ne pas avoir à l’expliquer, c’est pour l’environnement.

#     Mais j’ai également modifié la ligne  listen. J’ai indiqué qu’il devait écouter au port de WordPress, le 9000.

#     Grosso modo ca donne :    listen=wordpress:9000
# )
EXPOSE 9000
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

